app.py
from flask import Flask
from views import main

app = Flask(__name__)
app.register_blueprint(main)

if __name__ == "__main__":
    app.run(debug=True)

views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for

main = Blueprint("main", __name__)

@main.route("/")
def home():
    country = request.args.get("country")
    source = request.args.get("source")  
    return render_template("index.html", country=country, source=source)

@main.route("/about")
def about():
    context = {
        "name": "Isiakpona Chuks",
        "description": "With expertise in web and mobile development (ReactApp, AngularApp, Python), as well as being a Google Digital Marketing and e-commerce Specialist and Google UX Designer Specialist, I am committed to continuous learning and skill enhancement. My focus on detail and dedication to excellence align with company standards. Proficient in Microsoft Office Suite, Google Workspace, and equipped with strong communication, writing, analytical, and critical thinking skills, I am well-prepared to contribute to your team's success.",
    }
    return render_template("about.html", context=context)

@main.route('/about-us')
def about_us():
    return redirect(url_for("main.about"))

@main.route("/contact")
def contact():
    return render_template("contact.html")

@main.route("/portfolio")
def portfolio():
    projects_list = [
        {'name': 'Cinemahub', 'description': 'This is the first project.', 'endpoint': 'cinemahub'},
        {'name': 'Codebook', 'description': 'This is the second project.', 'endpoint': 'codebook'},
        {'name': 'Taskmate', 'description': 'This is the third project.', 'endpoint': 'taskmate'},
        {'name': 'Recipebook', 'description': 'This is the fourth project.', 'endpoint': 'recipebook'},
    ]
    return render_template("portfolio.html", projects=projects_list)

@main.route("/portfolio/<project>")
def project(project):
    projects_lst = ["cinemahub", "codebook", "taskmate", "recipebook"]
    if project in projects_lst:
        return render_template(f"portfolio/{project}.html")
    else:
        return redirect("/404")
    
@main.route('/portfolio/json')
def portfolio_json():
    projects = {
        "cinemahub": {
            "langauge": "python",
            "framework": "django",
            "status": "completed"
        },
        "codebook": {
            "langauge": "javascript",
            "framework": "react",
            "status": "learning"
        }
    }
    return jsonify(projects)
    
@main.route("/s")
def search():
    keyword = request.args.get("k")
    return f"{keyword}"

@main.route('/404')
def not_found_404():
    return render_template("404.html"), 404

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1>About {{ context.name }}</h1>
    <img src="{{ url_for('static', filename='images/about.jpg') }}" alt="">
    <p>{{ context.description }}</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Portfolio</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for('main.about') }}">About</a>
                </li>
                <li>
                    <a href="{{ url_for('main.contact') }}">Contact</a>
                </li>
                <li>
                    <a href="{{ url_for('main.portfolio') }}">Portfolio</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>    
    <footer>
        <p>&copy; 2024 - Isiakpona's Portfolio</p>
    </footer>    
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Let's Talk!</h1>
    <p>I'm always open to discussing new projects or opportunities. Feel free to reach out!</p>
    <p><strong>Email:</strong>juliusrlnd@gmail.com.</p>
    <p><strong>LinkedIn:</strong><a href="https://www.linkedin.com/in/isiakpona-chuks-14b93235" target="_blank">Profile</a>.</p>
    <p><strong>Github:</strong><a href="https://github.com/providingperspectives" target="_blank">Github Projects</a>.</p>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Hi, I'm Isiakpona Chuks!</h1>
    <p>I build web applications with Python, ReactApp, AngularApp and Django REST Framework, nodeJS for backend // JavaScript for frontend</p>
    <p>I also develop mobileApp Framework, Artificial Intelligence and Ethical Hacking. </p>

    {% if country == "Nigeria" %}
        <h1>Currency is NGN</h1>
    {% elif country == "usa" %}
        <h1>Currency is USD</h1>
    {% else %}
        <h1>Your default currency set to BTC!</h1>
    {% endif %}

    {% if source %}
        <h1>Thanks for visting through {{ source }}</h1>
    {% endif %}
{% endblock %}

templates/portfolio.html
{% extends 'base.html' %}

{% block title %}Portfolio{% endblock %}

{% block content %}

    <section>
        <h1>Portfolio</h1>
        <p>Hi! I'm Isiakpona Chuks, a passionate software developer specializing, 
            in full-stack development, mobile app development, Artificial intelligence, 
            and machine learning. With 8 years of experience, I thrive on creating efficient, 
            scalable, and user-friendly software solutions. My expertise lies in JavaScript, Python, 
            Angular, React, and Node.js, and I'm always eager to learn and adapt to new technologies.</p>
    </section>

    <section class="projects">
        <h1>Projects</h1>
        {% for project in projects %}
            <div class="project">
                <h2><a href="portfolio/{{ project.endpoint }}">{{ project.name }}</a></h2>
                <p>{{ project.description }}</p>
            </div>
        {% endfor %}
    </section>    
    
{% endblock %}






    

templates/portfolio/cinemahub.html
{% extends 'base.html' %}

{% block title %}Cinema-Hub Project{% endblock %}

{% block content %}
    <h1>About Cinema-hub</h1>
    <img src="{{ url_for('static', filename='images/project.jpg') }}" alt="">
    <p>Cinemahub is a full functional movieApp platform built exclusively with ReactApp with RESTAPI Server and hosted on netlifyApp
        check it out &nbsp;<a href="https://cinema-hub-chuks.netlify.app" target="_blank">here</a></p>
{% endblock %}

templates/portfolio/codebook.html
{% extends 'base.html' %}

{% block title %}CodeBook Project{% endblock %}

{% block content %}
    <h1>About CodeBook</h1>
    <img src="{{ url_for('static', filename='images/codebook.jpg') }}" alt="">
    <p>CodeBook is a full functional ebook platform built exclusively with ReactApp deployed on Render Server and hosted on netlifyApp
        check it out &nbsp;<a href="https://codebook-hub-ch.netlify.app" target="_blank">here</a>
    </p>
{% endblock %}

templates/portfolio/recipebook.html
{% extends 'base.html' %}

{% block title %}Recipebook Project{% endblock %}

{% block content %}
    <h1>About taskmate</h1>
    <img src="{{ url_for('static', filename='images/project.jpg') }}" alt="">
    <p>Recipebook is a full recipe project with AngularApp deployed on FirebaseApp check it out &nbsp;<a href="https://mypro-81325.web.app/auth" target="_blank">here</a>
    </p>
{% endblock %}

templates/portfolio/taskmate.html
{% extends 'base.html' %}

{% block title %}CodeBook Project{% endblock %}

{% block content %}
    <h1>About taskmate</h1>
    <img src="{{ url_for('static', filename='images/taskmate.jpg') }}" alt="">
    <p>Taskmate is a full task project with ReactApp deployed on netlifyApp check it out &nbsp;<a href="https://task-chuks.netlify.app" target="_blank">here</a>
    </p>
{% endblock %}